name: Build and deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Build Storybook
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run build-storybook
        env:
          NODE_ENV: production

      - name: Build Lib
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run build

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          package: lib/package.json
          token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
